- src/builtins.py
- src/parser.py
> Updated source files for better code organization

- examples/01_basics.so
- src/parser.py
> Fix modulo operator

- Dockerfile
- README.md
- docker-compose.yml
> Docker setup

- .editorconfig
- .flake8
- .pylintrc
- requirements-dev.txt
- requirements.txt
> Add development configuration files

- README.md
- setup.py
- soplang.spec
- windows/README.md
- windows/WINDOWS_BUILD_GUIDE.md
- windows/build_windows.bat
- windows/build_windows.ps1
- windows/file_association.reg
- windows/prepare_logos.bat
- windows/prepare_logos.ps1
- windows/soplang_cmd.bat
- windows/soplang_setup.iss
- windows/test_windows_build.ps1
> Add Windows build support

- src/runtime/shell.py
- windows/file_association.reg
- windows/soplang_setup.iss
> Windows build

- windows/create_shortcut.bat
- windows/file_association.reg
- windows/soplang_cmd.bat
- windows/soplang_launcher.bat
- windows/soplang_setup.iss
> Fix Soplang launcher scripts to properly run interactive shell

- README.md
- build.sh
- linux/README.md
- linux/build_linux.sh
- linux/prepare_logos.sh
- linux/requirements_linux.txt
> Add Linux build support with deb package creation

- build.sh
- macos/README.md
- macos/build_macos.sh
- macos/prepare_logos.sh
- macos/requirements_macos.txt
> Add macOS build support with app bundle and DMG creation

- tests/runners/run_all_tests.py
- tests/test_interpreter.py
- tests/test_lexer.py
- tests/test_parser.py
> Fix failing tests to match actual implementation behavior

- .github/workflows/docker-build.yml
- .github/workflows/release.yml
- Dockerfile
- README.md
- docs/RELEASE_PROCESS.md
- docs/docker.md
> feat: Implement Docker automation for builds and releases

- README.md
- docs/examples/EXAMPLES.md
- docs/language/grammar.md
- docs/language/keywords.md
- docs/testing/EXAMPLES.md
- examples/10_functions.sop
- examples/errors/04_runtime_errors.sop
- examples/errors/05_control_flow_errors.sop
- examples/errors/06_error_handling.sop
- grammar.ebnf
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/utils/errors.py
- tests/test_interpreter.py
> Rename howl to hawl and soo_celi to celi

- README.md
- docs/examples/EXAMPLES.md
- docs/language/grammar.md
- docs/language/keywords.md
- docs/testing/EXAMPLES.md
- examples/10_functions.sop
- examples/errors/04_runtime_errors.sop
- examples/errors/05_control_flow_errors.sop
- examples/errors/06_error_handling.sop
- grammar.ebnf
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/utils/errors.py
- tests/test_interpreter.py
> Soo celi to celi

- docs/language/grammar.md
- docs/language/keywords.md
- grammar.ebnf
- src/stdlib/builtins.py
> Rename waxba to maran

- docs/examples/EXAMPLES.md
- docs/examples/TEST_EXAMPLES_README.md
- docs/language/grammar.md
- docs/language/keywords.md
- docs/testing/EXAMPLES.md
- examples/08_for_loops.sop
- examples/09_while_loops.sop
- examples/errors/05_control_flow_errors.sop
- grammar.ebnf
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/utils/errors.py
> Rename sii_wad to soco

- docs/examples/EXAMPLES.md
- docs/examples/TEST_EXAMPLES_README.md
- docs/language/grammar.md
- docs/language/keywords.md
- docs/testing/DEBUGGING.md
- docs/testing/EXAMPLES.md
- examples/08_for_loops.sop
- examples/11_list_operations.sop
- examples/errors/05_control_flow_errors.sop
- grammar.ebnf
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/runtime/interpreter.py
- src/utils/errors.py
- tests/test_interpreter.py
- tests/test_parser.py
> Rename ku_celi to kuceli

- docs/language/grammar.md
- docs/language/keywords.md
- docs/testing/EXAMPLES.md
- examples/11_list_operations.sop
- grammar.ebnf
- src/stdlib/builtins.py
> Rename iskuxir to kudar

- csrc/stdlib/builtins.c
- csrc/utils/errors.c
- docs/examples/EXAMPLES.md
- docs/examples/TEST_EXAMPLES_README.md
- docs/language/keywords.md
- docs/testing/EXAMPLES.md
- examples/03_type_checking.sop
- examples/12_object_operations.sop
- examples/13_type_conversion.sop
- examples/15_user_input.sop
- src/runtime/interpreter.py
- src/stdlib/builtins.py
- src/utils/errors.py
🔁Rename nuuc to nooc
- 
- 
- 
Fixes #ISSUE_ID
> 🔁Rename nuuc to nooc

- examples/02_static_typing.sop
- examples/15_user_input.sop
- src/core/lexer.py
- src/core/parser.py
> Fixed keywords

- examples/05_comparison_operators.sop
- examples/06_logical_operators.sop
- examples/08_for_loops.sop
- examples/14_comparison_assignment.sop
- src/stdlib/builtins.py
> fixed examples

- examples/08_for_loops.sop
- examples/11_list_operations.sop
- grammar.ebnf
- src/core/parser.py
> refactor: remove  and apply new parentheses-based loop syntax

- examples/08_for_loops.sop
- grammar.ebnf
- src/core/parser.py
> refactor: replace `by` with `::` in loop step syntax

- examples/02_static_typing.sop
- examples/03_type_checking.sop
- examples/04_arithmetic_operators.sop
- examples/05_comparison_operators.sop
- examples/06_logical_operators.sop
- examples/07_conditional_statements.sop
- examples/09_while_loops.sop
- examples/10_functions.sop
- examples/13_type_conversion.sop
- examples/14_comparison_assignment.sop
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/stdlib/builtins.py
> refactor: clarify number types with `tiro` and `jajab`

- examples/15_switch_case.sop
- grammar.ebnf
- src/core/ast.py
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/runtime/interpreter.py
> feat: add `dooro (x)` / `xaalad` switch-case syntax

- docs/language/grammar.md
- docs/language/keywords.md
- examples/16_list_copy.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add `nuqul()` method for shallow copying lists

- docs/language/grammar.md
- docs/language/keywords.md
- examples/18_list_clear.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add `nadiifi()` to clear all items from a list

- docs/language/grammar.md
- docs/language/keywords.md
- examples/17_list_reverse.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add `rog()` to reverse lists in-place

- docs/language/grammar.md
- docs/language/keywords.md
- examples/18_list_sort.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add `habee()` method to sort lists in-place

- examples/19_list_filter.sop
- examples/19_list_filter_complex.sop
- examples/return_test.sop
- src/core/parser.py
- src/runtime/interpreter.py
- src/stdlib/builtins.py
> 94 add shaandhee method for listsarrays

- examples/20_constants.sop
- examples/21_practical_constants.sop
- examples/22_constant_reassignment_test.sop
- examples/23_constant_type_check.sop
- examples/24_constant_type_error_test.sop
- examples/25_constant_type_error.sop
- src/core/ast.py
- src/core/lexer.py
- src/core/parser.py
- src/core/tokens.py
- src/runtime/interpreter.py
- src/utils/errors.py
> 108 add madoor keyword for constant variables

- examples/26_list_slice.sop
- src/stdlib/builtins.py
> feat: add `jar(start, end)` method to slice lists

- examples/27_list_transform.sop
- src/runtime/interpreter.py
- src/stdlib/builtins.py
> 91 add aaddin method for listsarrays

- examples/28_list_raadso_and_negative_indexing.sop
- src/runtime/interpreter.py
- src/stdlib/builtins.py
> feat: add 'raadso()' and support negative indexing in lists

- docs/language/grammar.md
- docs/language/keywords.md
- examples/29_object_copy.sop
- grammar.ebnf
- src/stdlib/builtins.py
> 95 add nuqul method for objects

- docs/language/grammar.md
- docs/language/keywords.md
- examples/31_object_values.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add walax.qiime() method for getting all values from an object

- docs/language/grammar.md
- docs/language/keywords.md
- examples/32_object_entries.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: implement `lamaane()` to return [key, value] pairs from walax

- docs/language/keywords.md
- examples/33_string_methods.sop
- grammar.ebnf
- src/runtime/interpreter.py
- src/stdlib/builtins.py
> feat: implement `qeybi()` method to split strings by delimiter

- docs/language/keywords.md
- examples/35_math_floor.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add `daji()` to round numbers down to nearest integer

- docs/language/keywords.md
- examples/36_math_ceil.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: add `kor()` to round numbers up to the nearest integer

- docs/language/keywords.md
- examples/37_string_endswith.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: implement `dhamaad()` to check string suffix match

- docs/language/keywords.md
- examples/41_string_slice.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: implement `jar()` to slice substrings by index

- docs/language/keywords.md
- examples/43_random_function.sop
- grammar.ebnf
- src/stdlib/builtins.py
> feat: implement `kudhow()` for random number and list item selection

- SOPLANG_MVP.md
- docs/language/keywords.md
- docs/testing/EXAMPLES.md
- examples/12_object_operations.sop
- examples/30_object_clear.sop
- grammar.ebnf
- src/stdlib/builtins.py
> Rename tirtir() → tir()

- docs/language/keywords.md
- examples/28_list_raadso_and_negative_indexing.sop
- grammar.ebnf
- src/stdlib/builtins.py
> Rename raadso() → muuji()

- docs/language/keywords.md
- examples/43_random_function.sop
- grammar.ebnf
- src/stdlib/builtins.py
> fix: rename kudhow to xul in navbar

- Dockerfile
- examples/21_practical_constants.sop
- main.py
- setup.py
- src/core/version.py
- windows/soplang_setup.iss
> preparing the soplang 2 release
